apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: 831282768463.dkr.ecr.us-east-1.amazonaws.com/test:latest
          ports:
            - containerPort: 5000
          env:
          - name: API_URL
            valueFrom:
              secretKeyRef:
                name: pod-secret
                key: API_URL
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: pod-secret
                key: API_KEY      
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer